#!/usr/bin/env node
// ============================================================================
// scripts/build-tokens.ts
// Reads tokens/*.json → generates src/styles/tokens.css
// Usage: npm run tokens
// ============================================================================

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(process.cwd());
const TOKENS_DIR = join(ROOT, 'tokens');
const OUTPUT_FILE = join(ROOT, 'src', 'styles', 'tokens.css');

function readJSON(filename: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(TOKENS_DIR, filename), 'utf-8'));
}

function flattenObject(
  obj: Record<string, unknown>,
  prefix: string,
  separator = '-'
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}${separator}${key}` : key;
    if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value as Record<string, unknown>, fullKey, separator));
    } else {
      result[fullKey] = String(value);
    }
  }
  return result;
}

const colors = readJSON('colors.json') as { color: Record<string, unknown> };
const spacing = readJSON('spacing.json') as { space: Record<string, unknown> };
const radius = readJSON('radius.json') as { radius: Record<string, unknown> };
const typography = readJSON('typography.json');
const shadow = readJSON('shadow.json') as { shadow: Record<string, unknown> };
const motion = readJSON('motion.json') as { motion: Record<string, unknown> };
const zIndex = readJSON('z-index.json') as { z: Record<string, unknown> };

// Light mode color vars
const lightColors = Object.entries(colors.color)
  .filter(([k]) => !k.startsWith('dark-'))
  .map(([k, v]) => `  --color-${k}: ${v};`)
  .join('\n');

// Dark mode overrides
const darkColorMap: Record<string, string> = {
  'bg': 'dark-bg',
  'surface': 'dark-surface',
  'card': 'dark-card',
  'text-primary': 'dark-text',
  'text-secondary': 'dark-text-secondary',
  'border': 'dark-border',
  'divider': 'dark-border',
};
const darkColors = Object.entries(darkColorMap)
  .map(([light, dark]) => `  --color-${light}: var(--color-${dark});`)
  .join('\n');

// All dark raw values
const darkRawColors = Object.entries(colors.color)
  .filter(([k]) => k.startsWith('dark-'))
  .map(([k, v]) => `  --color-${k}: ${v};`)
  .join('\n');

// Spacing
const spacingVars = Object.entries(spacing.space)
  .map(([k, v]) => `  --space-${k}: ${v};`)
  .join('\n');

// Radius
const radiusVars = Object.entries(radius.radius)
  .map(([k, v]) => `  --radius-${k}: ${v};`)
  .join('\n');

// Typography sizes
const typo = typography as { size: Record<string, string>; weight: Record<string, string>; 'line-height': Record<string, string> };
const fontSizeVars = Object.entries(typo.size)
  .map(([k, v]) => `  --text-${k}: ${v};`)
  .join('\n');
const fontWeightVars = Object.entries(typo.weight)
  .map(([k, v]) => `  --weight-${k}: ${v};`)
  .join('\n');
const lineHeightVars = Object.entries(typo['line-height'])
  .map(([k, v]) => `  --leading-${k}: ${v};`)
  .join('\n');

// Shadows
const shadowVars = Object.entries(shadow.shadow)
  .map(([k, v]) => `  --shadow-${k}: ${v};`)
  .join('\n');

// Motion
const flatMotion = flattenObject(motion.motion as Record<string, unknown>, '');
const motionVars = Object.entries(flatMotion)
  .map(([k, v]) => `  --motion-${k}: ${v};`)
  .join('\n');

// Z-index
const zVars = Object.entries(zIndex.z)
  .map(([k, v]) => `  --z-${k}: ${v};`)
  .join('\n');

const css = `/* ============================================================================
 * ShopMind Design Tokens — Auto-generated by scripts/build-tokens.ts
 * DO NOT EDIT MANUALLY — Run \`npm run tokens\` to regenerate
 * Source: tokens/*.json
 * ============================================================================ */

:root {
  /* ── Colors — Light Mode ──────────────────────────────────────────────── */
${lightColors}
${darkRawColors}

  /* ── Spacing (8px grid) ───────────────────────────────────────────────── */
${spacingVars}

  /* ── Border Radius ────────────────────────────────────────────────────── */
${radiusVars}

  /* ── Typography ───────────────────────────────────────────────────────── */
${fontSizeVars}
${fontWeightVars}
${lineHeightVars}

  /* ── Shadows / Elevation ──────────────────────────────────────────────── */
${shadowVars}

  /* ── Motion ───────────────────────────────────────────────────────────── */
${motionVars}

  /* ── Z-Index Scale ────────────────────────────────────────────────────── */
${zVars}
}

/* ── Dark Mode Overrides ──────────────────────────────────────────────────── */

.dark,
[data-theme="dark"] {
${darkColors}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkColors}
  }
}
`;

// Ensure output dir exists
mkdirSync(join(ROOT, 'src', 'styles'), { recursive: true });
writeFileSync(OUTPUT_FILE, css, 'utf-8');

console.log(`✅ tokens.css generated → ${OUTPUT_FILE}`);
console.log(`   Colors: ${Object.keys(colors.color).length} tokens`);
console.log(`   Spacing: ${Object.keys(spacing.space).length} tokens`);
console.log(`   Motion: ${Object.keys(flatMotion).length} tokens`);
